
volumes:
 mosquitto-data:

#networks:
  #iot:
   #name: iot
   
services:
 mosquitto: 
  image: eclipse-mosquitto
  container_name: mosquitto-mqtt-broker
  restart: unless-stopped
  ports:
   - 1883:1883
  #networks:
   #- iot
  volumes:
   - mosquitto-data:/mosquitto/data
   - ./config:/mosquitto/config  
   #- mosquitto-logs:/mosquitto/logs  //uncomment to store logs
   #- ./volumes/mosquitto/pwfile:/mosquitto/pwfile

 
