version: "3.7"

services:
  node-red:
   container_name: nodered
    image: nodered/node-red:latest
    
    ports:
      - "1880:1880"
    networks:
     # - node-red-net
    volumes:
      - NodeREDdata:/data 

volumes:
  node-red-data:

networks:
 # node-red-net:
